[project]
name = 'Decentralized-Cosmic-Evolutionary-Guidance-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.civilizational-development-pathway]
path = 'contracts/civilizational-development-pathway.clar'
clarity_version = 2
epoch = 2.5

[contracts.universal-fitness-function]
path = 'contracts/universal-fitness-function.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
